#!/usr/bin/python

import sys
import os

import make_meeting

remote = os.environ['REMOTE_USER']

commands = {
    'make-public-meeting': lambda *args: make_meeting_remctl(True, *args),
    'make-private-meeting': lambda *args: make_meeting_remctl(False, *args),
}

def make_meeting_remctl(public, shortname, longname=None):
    args = make_meeting.MakeMeetingArgs(shortname, public=public, longname=longname)
    meeting = make_meeting.make_meeting(args)
    if meeting:
        meeting.set_access(remote, make_meeting.ACL_ALL)
        make_meeting.set_default_perms(meeting)
        print meeting.get_acl()

if __name__ == '__main__':
    command = sys.argv[1]
    commands[command](*sys.argv[2:])
