#!/usr/bin/python

import sys
import os

import make_meeting

remote = os.environ['REMOTE_USER']

command = sys.argv[1]
public = (command == 'make-public-meeting')
longname = sys.argv[3] if len(sys.argv) == 4 else None
args = make_meeting.MakeMeetingArgs(sys.argv[2], public=public, longname=longname)
meeting = make_meeting.make_meeting(args)
if meeting:
    meeting.set_access(remote, make_meeting.ACL_ALL)
    make_meeting.set_default_perms(meeting)
    print meeting.get_acl()
